name: Continuous Integration

on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
      - reopened

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing all the things..."
